In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings as wr
wr.filterwarnings('ignore')

Separate x(Gender, Height) and y (y=Weight)
Train = 70%, Test = 30%
Apply Linear Regression
Evaluate the Model (Testing and training Accuracy, MSE for testing)
Apply KNN Regressor: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html
Evaluate the Model (Testing and training Accuracy, MSE for testing)
Compare KNN & Linear regression with the KNN model and Linear regression as well.

# Step 01: Regression

In [2]:
df1 = pd.read_csv('weight-height.csv')
df1.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [3]:
df2=df1.copy()

In [4]:
df1.Gender.nunique() #to see number of unique value

2

In [5]:
df1.Gender.unique() #to find the name of unique value

array(['Male', 'Female'], dtype=object)

In [6]:
df1.Gender= df1.Gender.replace(['Male','Female'],[2,1]) #to replace the unique value with code number 1,2 for conducting regression
df1.head()

Gender     Height      Weight
0       2  73.847017  241.893563
1       2  68.781904  162.310473
2       2  74.110105  212.740856
3       2  71.730978  220.042470
4       2  69.881796  206.349801

In [7]:
y= df1[['Weight']] #to seperate y value

In [8]:
x = df1.drop('Weight', axis=1)

In [9]:
x.head() #to seperate x value

Gender     Height
0       2  73.847017
1       2  68.781904
2       2  74.110105
3       2  71.730978
4       2  69.881796

In [10]:
y.head()

Weight
0  241.893563
1  162.310473
2  212.740856
3  220.042470
4  206.349801

In [11]:
from sklearn.model_selection import train_test_split as tts

In [12]:
xtrain, xtest, ytrain, ytest= tts(x,y,test_size=0.3,random_state=1) #to split testing and training value

In [13]:
from sklearn.linear_model import LinearRegression #to conduct regression
reg= LinearRegression()

In [14]:
reg.fit(xtrain, ytrain)

LinearRegression()

In [15]:
m = reg.coef_  #coefficient in linear regression equation

In [16]:
c = reg.intercept_  #intercept in Linear Regression equiation

In [17]:
m

array([[19.34359322,  5.96887438]])

In [18]:
c

array([-263.89640226])

In [19]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [20]:
linear_test_mse = mean_squared_error(ytest, reg.predict(xtest)) #MSE for test
linear_test_mse

99.67250998070031

In [21]:
linear_test_accuracy=reg.score(xtest,ytest) #test accuracy
linear_test_accuracy

0.905995960709116

In [22]:
linear_train_accuracy= reg.score(xtrain, ytrain) #train accuracy
linear_train_accuracy

0.8972135459668117

In [23]:
reg.predict([[1,86.4]])

array([[271.15793775]])

# KNN regression

In [24]:
from sklearn.neighbors import KNeighborsRegressor 
KNR=KNeighborsRegressor()

In [25]:
xtrain, xtest, ytrain, ytest= tts(x,y,test_size=0.3,random_state=0)

In [26]:
KNR.fit(xtrain,ytrain)#KNN regression
y_pred=KNR.predict(xtest)

In [27]:
KNR_train_accuracy= KNR.score(xtrain,ytrain) #train accuracy
KNR_train_accuracy

0.9184951353192796

In [28]:
KNR_test_accuracy=KNR.score(xtest,ytest)#test accuracy
KNR_test_accuracy

0.8805893134749361

In [29]:
KNR_mse = mean_squared_error(ytest,y_pred)#MSE for testing
KNR_mse

125.33079203407898

In [30]:
from sklearn.metrics import r2_score

In [31]:
r2_score(y_pred,ytest) #to measure accuracy

0.8704019205294287

In [32]:
print("Comparison between Linear and KNN: ")

print("\nLinear Regression Training Accuracy:", linear_train_accuracy)
print("KNN Regressor Training Accuracy:", KNR_train_accuracy)

print("\nLinear Regression Testing Accuracy:", linear_test_accuracy)
print("KNN Regressor Testing Accuracy:", KNR_test_accuracy)

print("\nLinear Regression MSE:", linear_test_mse)
print("KNN Regressor MSE:", KNR_mse)

Comparison between Linear and KNN: 

Linear Regression Training Accuracy: 0.8972135459668117
KNN Regressor Training Accuracy: 0.9184951353192796

Linear Regression Testing Accuracy: 0.905995960709116
KNN Regressor Testing Accuracy: 0.8805893134749361

Linear Regression MSE: 99.67250998070031
KNN Regressor MSE: 125.33079203407898


Separate x and (y=Gender)
Train = 70%, Test = 30%
Apply KNN Classifier
Evaluate the Model by only Accuracy.
Apply KNN Classifier: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

# Step 02: Classification

In [33]:
df2.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [34]:
Y= df2[['Gender']] #to seperate y value

In [35]:
X = df2.drop('Gender', axis=1)

In [36]:
X.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [37]:
Y.head()

Gender
0   Male
1   Male
2   Male
3   Male
4   Male

In [38]:
from sklearn.neighbors import KNeighborsClassifier

In [39]:
KNC= KNeighborsClassifier(5)

In [40]:
Xtrain, Xtest, Ytrain, Ytest= tts(X,Y,test_size=0.3,random_state=0) #to split training and testing data

In [41]:
KNC.fit(Xtrain,Ytrain)
Y_pred=KNC.predict(Xtest) #to train model

In [42]:
KNC.predict([[65.9, 202]])

array(['Male'], dtype=object)